# Generated by Django 3.2 on 2023-09-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
