# Generated by Django 3.2 on 2023-09-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20230920_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[('Создан', 1), ('Отправлен', 2), ('Ошибка', 3)], default=1, verbose_name='Статус'),
        ),
    ]
