# Generated by Django 3.2 on 2023-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Создан'), (2, 'Отправлен'), (3, 'Ошибка')], default=1, verbose_name='Статус'),
        ),
    ]
