# Generated by Django 3.2 on 2023-09-01 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда создан')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда изменён')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('py_file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['py'])], verbose_name='Python файл')),
                ('status', models.SmallIntegerField(choices=[('Создан', 1), ('Перезаписан', 2), ('Удален', 3)], default=1, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
