# Generated by Django 3.2 on 2023-09-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
