# Generated by Django 3.2 on 2023-09-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20230904_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
